on: [push]

jobs:
  build:
    name: Build (MSYS2)
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            msys/gcc
            mingw64/mingw-w64-x86_64-gcc
            make
      - run: ./configure
      - run: make
